version: '3.8'

services:
  web:
    build: .
    container_name: smartlock_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      # Linha mágica: Salva os modelos de IA na sua máquina para não precisar baixar de novo
      - ~/.deepface:/root/.deepface  
    ports:
      - "8000:8000"

